version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: user_service_db
    environment:
      POSTGRES_DB: user_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  user-service:
    build: 
      context: ./services/user_services
      dockerfile: Dockerfile
    container_name: user_service
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./services/user_services:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_NAME=user_service
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data: